accounts:
  - name: alice
    coins: ["1000000000uname"]
  - name: jack
    coins: ["1000000000uname"]
validator:
  name: jack
  staked: "10000000uname"
faucet:
  name: alice 
  coins: ["5000000uname"]
