version: "3.9"
services:
  chain:
    image: starp
    ports:
      - "12345:12345"
      - "8080:8080"
      - "1317:1317"
      - "26656:26656"
      - "26657:26657"
    volumes:
      - .:/app
    command: tail -f /dev/null